package com.workflow.stress

import java.io.PrintWriter
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.ResultSet
import java.sql.ResultSetMetaData
import java.sql.SQLException
import java.time.Duration
import java.util.concurrent.CopyOnWriteArrayList
import java.util.concurrent.atomic.AtomicInteger
import java.util.logging.Logger
import javax.sql.DataSource

/**
 * SQL-level fault injection for stress tests.
 *
 * Wraps a JDBC DataSource and intercepts PreparedStatement execution.
 * Registered fault rules match SQL patterns and inject failures, delays,
 * or empty results — enabling typed fault injection that Toxiproxy
 * (network-level) cannot provide.
 *
 * Inspired by MicroRaft's typed message filtering and etcd/raft's
 * pure state machine testability.
 */
class FaultInjector {

    private val rules = CopyOnWriteArrayList<FaultRule>()

    fun onSql(pattern: String): FaultRule {
        val rule = FaultRule(Regex(pattern))
        rules.add(rule)
        return rule
    }

    fun reset() {
        rules.clear()
    }

    internal fun checkBeforeExecute(sql: String) {
        for (rule in rules) {
            if (rule.pattern.containsMatchIn(sql)) {
                rule.applyBeforeExecute(sql)
            }
        }
    }

    internal fun shouldReturnEmpty(sql: String): Boolean {
        for (rule in rules) {
            if (rule.pattern.containsMatchIn(sql)) {
                if (rule.tryConsumeEmpty()) return true
            }
        }
        return false
    }
}

class FaultRule(internal val pattern: Regex) {

    private var failRemaining = AtomicInteger(0)
    private var failException: SQLException = SQLException("injected fault")
    private var delayDuration: Duration? = null
    private var emptyRemaining = AtomicInteger(0)
    private var failOnNth: Int = 0
    private var failNthException: SQLException = SQLException("injected fault")
    private val executionCount = AtomicInteger(0)

    fun failNext(times: Int = 1, exception: SQLException = SQLException("injected fault")): FaultRule {
        failRemaining.set(times)
        failException = exception
        return this
    }

    fun delay(duration: Duration): FaultRule {
        delayDuration = duration
        return this
    }

    fun returnEmpty(times: Int = 1): FaultRule {
        emptyRemaining.set(times)
        return this
    }

    fun failNth(n: Int, exception: SQLException = SQLException("injected fault")): FaultRule {
        failOnNth = n
        failNthException = exception
        return this
    }

    internal fun applyBeforeExecute(sql: String) {
        // Delay
        val delay = delayDuration
        if (delay != null) {
            Thread.sleep(delay.toMillis())
        }

        // Fail next N
        if (failRemaining.getAndUpdate { if (it > 0) it - 1 else 0 } > 0) {
            throw failException
        }

        // Fail Nth execution
        if (failOnNth > 0) {
            val count = executionCount.incrementAndGet()
            if (count == failOnNth) {
                throw failNthException
            }
        }
    }

    internal fun tryConsumeEmpty(): Boolean =
        emptyRemaining.getAndUpdate { if (it > 0) it - 1 else 0 } > 0
}

/**
 * DataSource wrapper that routes connections through FaultInjector.
 */
class FaultInjectingDataSource(
    private val delegate: DataSource,
    private val injector: FaultInjector,
) : DataSource {

    override fun getConnection(): Connection =
        FaultInjectingConnection(delegate.connection, injector)

    override fun getConnection(username: String?, password: String?): Connection =
        FaultInjectingConnection(delegate.getConnection(username, password), injector)

    override fun getLogWriter(): PrintWriter? = delegate.logWriter
    override fun setLogWriter(out: PrintWriter?) { delegate.logWriter = out }
    override fun setLoginTimeout(seconds: Int) { delegate.loginTimeout = seconds }
    override fun getLoginTimeout(): Int = delegate.loginTimeout
    override fun getParentLogger(): Logger = delegate.parentLogger
    override fun <T : Any?> unwrap(iface: Class<T>?): T = delegate.unwrap(iface)
    override fun isWrapperFor(iface: Class<*>?): Boolean = delegate.isWrapperFor(iface)
}

/**
 * Connection wrapper that creates fault-injecting PreparedStatements.
 */
private class FaultInjectingConnection(
    private val delegate: Connection,
    private val injector: FaultInjector,
) : Connection by delegate {

    override fun prepareStatement(sql: String): PreparedStatement =
        FaultInjectingPreparedStatement(delegate.prepareStatement(sql), sql, injector)

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
        FaultInjectingPreparedStatement(delegate.prepareStatement(sql, autoGeneratedKeys), sql, injector)

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement =
        FaultInjectingPreparedStatement(
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency), sql, injector,
        )

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): PreparedStatement =
        FaultInjectingPreparedStatement(
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), sql, injector,
        )

    override fun prepareStatement(sql: String, columnNames: Array<out String>?): PreparedStatement =
        FaultInjectingPreparedStatement(delegate.prepareStatement(sql, columnNames), sql, injector)

    override fun prepareStatement(sql: String, columnIndexes: IntArray?): PreparedStatement =
        FaultInjectingPreparedStatement(delegate.prepareStatement(sql, columnIndexes), sql, injector)
}

/**
 * PreparedStatement wrapper that checks fault rules before execution.
 */
private class FaultInjectingPreparedStatement(
    private val delegate: PreparedStatement,
    private val sql: String,
    private val injector: FaultInjector,
) : PreparedStatement by delegate {

    override fun execute(): Boolean {
        injector.checkBeforeExecute(sql)
        if (injector.shouldReturnEmpty(sql)) return false
        return delegate.execute()
    }

    override fun executeQuery(): ResultSet {
        injector.checkBeforeExecute(sql)
        if (injector.shouldReturnEmpty(sql)) return EmptyResultSet(null)
        return delegate.executeQuery()
    }

    override fun executeUpdate(): Int {
        injector.checkBeforeExecute(sql)
        return delegate.executeUpdate()
    }

    override fun executeBatch(): IntArray {
        injector.checkBeforeExecute(sql)
        return delegate.executeBatch()
    }
}

/**
 * ResultSet that is always empty. Used by returnEmpty() fault rule.
 * Delegates metadata to the real result set's metadata for column info.
 */
private class EmptyResultSet(private val meta: ResultSetMetaData?) : ResultSet {
    override fun next(): Boolean = false
    override fun close() {}
    override fun wasNull(): Boolean = true
    override fun getMetaData(): ResultSetMetaData? = meta

    // All getters throw since next() is always false
    override fun getString(columnIndex: Int): String = throw SQLException("No current row")
    override fun getString(columnLabel: String?): String = throw SQLException("No current row")
    override fun getInt(columnIndex: Int): Int = throw SQLException("No current row")
    override fun getInt(columnLabel: String?): Int = throw SQLException("No current row")
    override fun getLong(columnIndex: Int): Long = throw SQLException("No current row")
    override fun getLong(columnLabel: String?): Long = throw SQLException("No current row")
    override fun getObject(columnIndex: Int): Any = throw SQLException("No current row")
    override fun getObject(columnLabel: String?): Any = throw SQLException("No current row")

    // Navigation — all return false/empty
    override fun isBeforeFirst(): Boolean = false
    override fun isAfterLast(): Boolean = true
    override fun isFirst(): Boolean = false
    override fun isLast(): Boolean = false
    override fun first(): Boolean = false
    override fun last(): Boolean = false
    override fun getRow(): Int = 0
    override fun previous(): Boolean = false
    override fun beforeFirst() {}
    override fun afterLast() {}
    override fun absolute(row: Int): Boolean = false
    override fun relative(rows: Int): Boolean = false
    override fun getFetchDirection(): Int = ResultSet.FETCH_FORWARD
    override fun setFetchDirection(direction: Int) {}
    override fun getFetchSize(): Int = 0
    override fun setFetchSize(rows: Int) {}
    override fun getType(): Int = ResultSet.TYPE_FORWARD_ONLY
    override fun getConcurrency(): Int = ResultSet.CONCUR_READ_ONLY
    override fun getHoldability(): Int = ResultSet.HOLD_CURSORS_OVER_COMMIT
    override fun isClosed(): Boolean = false
    override fun getStatement(): java.sql.Statement? = null
    override fun findColumn(columnLabel: String?): Int = throw SQLException("No current row")
    override fun rowUpdated(): Boolean = false
    override fun rowInserted(): Boolean = false
    override fun rowDeleted(): Boolean = false
    override fun getCursorName(): String = throw SQLException("No current row")
    override fun <T : Any?> unwrap(iface: Class<T>?): T = throw SQLException("Not a wrapper")
    override fun isWrapperFor(iface: Class<*>?): Boolean = false

    // Remaining getters — all throw
    override fun getBoolean(columnIndex: Int): Boolean = throw SQLException("No current row")
    override fun getBoolean(columnLabel: String?): Boolean = throw SQLException("No current row")
    override fun getByte(columnIndex: Int): Byte = throw SQLException("No current row")
    override fun getByte(columnLabel: String?): Byte = throw SQLException("No current row")
    override fun getShort(columnIndex: Int): Short = throw SQLException("No current row")
    override fun getShort(columnLabel: String?): Short = throw SQLException("No current row")
    override fun getFloat(columnIndex: Int): Float = throw SQLException("No current row")
    override fun getFloat(columnLabel: String?): Float = throw SQLException("No current row")
    override fun getDouble(columnIndex: Int): Double = throw SQLException("No current row")
    override fun getDouble(columnLabel: String?): Double = throw SQLException("No current row")
    @Deprecated("Use getBigDecimal without scale")
    override fun getBigDecimal(columnIndex: Int, scale: Int): java.math.BigDecimal = throw SQLException("No current row")
    override fun getBigDecimal(columnIndex: Int): java.math.BigDecimal = throw SQLException("No current row")
    @Deprecated("Use getBigDecimal without scale")
    override fun getBigDecimal(columnLabel: String?, scale: Int): java.math.BigDecimal = throw SQLException("No current row")
    override fun getBigDecimal(columnLabel: String?): java.math.BigDecimal = throw SQLException("No current row")
    override fun getBytes(columnIndex: Int): ByteArray = throw SQLException("No current row")
    override fun getBytes(columnLabel: String?): ByteArray = throw SQLException("No current row")
    override fun getDate(columnIndex: Int): java.sql.Date = throw SQLException("No current row")
    override fun getDate(columnLabel: String?): java.sql.Date = throw SQLException("No current row")
    override fun getDate(columnIndex: Int, cal: java.util.Calendar?): java.sql.Date = throw SQLException("No current row")
    override fun getDate(columnLabel: String?, cal: java.util.Calendar?): java.sql.Date = throw SQLException("No current row")
    override fun getTime(columnIndex: Int): java.sql.Time = throw SQLException("No current row")
    override fun getTime(columnLabel: String?): java.sql.Time = throw SQLException("No current row")
    override fun getTime(columnIndex: Int, cal: java.util.Calendar?): java.sql.Time = throw SQLException("No current row")
    override fun getTime(columnLabel: String?, cal: java.util.Calendar?): java.sql.Time = throw SQLException("No current row")
    override fun getTimestamp(columnIndex: Int): java.sql.Timestamp = throw SQLException("No current row")
    override fun getTimestamp(columnLabel: String?): java.sql.Timestamp = throw SQLException("No current row")
    override fun getTimestamp(columnIndex: Int, cal: java.util.Calendar?): java.sql.Timestamp = throw SQLException("No current row")
    override fun getTimestamp(columnLabel: String?, cal: java.util.Calendar?): java.sql.Timestamp = throw SQLException("No current row")
    override fun getAsciiStream(columnIndex: Int): java.io.InputStream = throw SQLException("No current row")
    override fun getAsciiStream(columnLabel: String?): java.io.InputStream = throw SQLException("No current row")
    @Deprecated("Use getCharacterStream")
    override fun getUnicodeStream(columnIndex: Int): java.io.InputStream = throw SQLException("No current row")
    @Deprecated("Use getCharacterStream")
    override fun getUnicodeStream(columnLabel: String?): java.io.InputStream = throw SQLException("No current row")
    override fun getBinaryStream(columnIndex: Int): java.io.InputStream = throw SQLException("No current row")
    override fun getBinaryStream(columnLabel: String?): java.io.InputStream = throw SQLException("No current row")
    override fun getWarnings(): java.sql.SQLWarning? = null
    override fun clearWarnings() {}
    override fun getCharacterStream(columnIndex: Int): java.io.Reader = throw SQLException("No current row")
    override fun getCharacterStream(columnLabel: String?): java.io.Reader = throw SQLException("No current row")
    override fun getObject(columnIndex: Int, map: MutableMap<String, Class<*>>?): Any = throw SQLException("No current row")
    override fun getObject(columnLabel: String?, map: MutableMap<String, Class<*>>?): Any = throw SQLException("No current row")
    override fun <T : Any?> getObject(columnIndex: Int, type: Class<T>?): T = throw SQLException("No current row")
    override fun <T : Any?> getObject(columnLabel: String?, type: Class<T>?): T = throw SQLException("No current row")
    override fun getRef(columnIndex: Int): java.sql.Ref = throw SQLException("No current row")
    override fun getRef(columnLabel: String?): java.sql.Ref = throw SQLException("No current row")
    override fun getBlob(columnIndex: Int): java.sql.Blob = throw SQLException("No current row")
    override fun getBlob(columnLabel: String?): java.sql.Blob = throw SQLException("No current row")
    override fun getClob(columnIndex: Int): java.sql.Clob = throw SQLException("No current row")
    override fun getClob(columnLabel: String?): java.sql.Clob = throw SQLException("No current row")
    override fun getArray(columnIndex: Int): java.sql.Array = throw SQLException("No current row")
    override fun getArray(columnLabel: String?): java.sql.Array = throw SQLException("No current row")
    override fun getURL(columnIndex: Int): java.net.URL = throw SQLException("No current row")
    override fun getURL(columnLabel: String?): java.net.URL = throw SQLException("No current row")
    override fun getRowId(columnIndex: Int): java.sql.RowId = throw SQLException("No current row")
    override fun getRowId(columnLabel: String?): java.sql.RowId = throw SQLException("No current row")
    override fun getNClob(columnIndex: Int): java.sql.NClob = throw SQLException("No current row")
    override fun getNClob(columnLabel: String?): java.sql.NClob = throw SQLException("No current row")
    override fun getSQLXML(columnIndex: Int): java.sql.SQLXML = throw SQLException("No current row")
    override fun getSQLXML(columnLabel: String?): java.sql.SQLXML = throw SQLException("No current row")
    override fun getNString(columnIndex: Int): String = throw SQLException("No current row")
    override fun getNString(columnLabel: String?): String = throw SQLException("No current row")
    override fun getNCharacterStream(columnIndex: Int): java.io.Reader = throw SQLException("No current row")
    override fun getNCharacterStream(columnLabel: String?): java.io.Reader = throw SQLException("No current row")

    // Update methods — all throw
    override fun updateNull(columnIndex: Int) = throw SQLException("Read-only")
    override fun updateNull(columnLabel: String?) = throw SQLException("Read-only")
    override fun updateBoolean(columnIndex: Int, x: Boolean) = throw SQLException("Read-only")
    override fun updateBoolean(columnLabel: String?, x: Boolean) = throw SQLException("Read-only")
    override fun updateByte(columnIndex: Int, x: Byte) = throw SQLException("Read-only")
    override fun updateByte(columnLabel: String?, x: Byte) = throw SQLException("Read-only")
    override fun updateShort(columnIndex: Int, x: Short) = throw SQLException("Read-only")
    override fun updateShort(columnLabel: String?, x: Short) = throw SQLException("Read-only")
    override fun updateInt(columnIndex: Int, x: Int) = throw SQLException("Read-only")
    override fun updateInt(columnLabel: String?, x: Int) = throw SQLException("Read-only")
    override fun updateLong(columnIndex: Int, x: Long) = throw SQLException("Read-only")
    override fun updateLong(columnLabel: String?, x: Long) = throw SQLException("Read-only")
    override fun updateFloat(columnIndex: Int, x: Float) = throw SQLException("Read-only")
    override fun updateFloat(columnLabel: String?, x: Float) = throw SQLException("Read-only")
    override fun updateDouble(columnIndex: Int, x: Double) = throw SQLException("Read-only")
    override fun updateDouble(columnLabel: String?, x: Double) = throw SQLException("Read-only")
    override fun updateBigDecimal(columnIndex: Int, x: java.math.BigDecimal?) = throw SQLException("Read-only")
    override fun updateBigDecimal(columnLabel: String?, x: java.math.BigDecimal?) = throw SQLException("Read-only")
    override fun updateString(columnIndex: Int, x: String?) = throw SQLException("Read-only")
    override fun updateString(columnLabel: String?, x: String?) = throw SQLException("Read-only")
    override fun updateBytes(columnIndex: Int, x: ByteArray?) = throw SQLException("Read-only")
    override fun updateBytes(columnLabel: String?, x: ByteArray?) = throw SQLException("Read-only")
    override fun updateDate(columnIndex: Int, x: java.sql.Date?) = throw SQLException("Read-only")
    override fun updateDate(columnLabel: String?, x: java.sql.Date?) = throw SQLException("Read-only")
    override fun updateTime(columnIndex: Int, x: java.sql.Time?) = throw SQLException("Read-only")
    override fun updateTime(columnLabel: String?, x: java.sql.Time?) = throw SQLException("Read-only")
    override fun updateTimestamp(columnIndex: Int, x: java.sql.Timestamp?) = throw SQLException("Read-only")
    override fun updateTimestamp(columnLabel: String?, x: java.sql.Timestamp?) = throw SQLException("Read-only")
    override fun updateAsciiStream(columnIndex: Int, x: java.io.InputStream?, length: Int) = throw SQLException("Read-only")
    override fun updateAsciiStream(columnLabel: String?, x: java.io.InputStream?, length: Int) = throw SQLException("Read-only")
    override fun updateAsciiStream(columnIndex: Int, x: java.io.InputStream?, length: Long) = throw SQLException("Read-only")
    override fun updateAsciiStream(columnLabel: String?, x: java.io.InputStream?, length: Long) = throw SQLException("Read-only")
    override fun updateAsciiStream(columnIndex: Int, x: java.io.InputStream?) = throw SQLException("Read-only")
    override fun updateAsciiStream(columnLabel: String?, x: java.io.InputStream?) = throw SQLException("Read-only")
    override fun updateBinaryStream(columnIndex: Int, x: java.io.InputStream?, length: Int) = throw SQLException("Read-only")
    override fun updateBinaryStream(columnLabel: String?, x: java.io.InputStream?, length: Int) = throw SQLException("Read-only")
    override fun updateBinaryStream(columnIndex: Int, x: java.io.InputStream?, length: Long) = throw SQLException("Read-only")
    override fun updateBinaryStream(columnLabel: String?, x: java.io.InputStream?, length: Long) = throw SQLException("Read-only")
    override fun updateBinaryStream(columnIndex: Int, x: java.io.InputStream?) = throw SQLException("Read-only")
    override fun updateBinaryStream(columnLabel: String?, x: java.io.InputStream?) = throw SQLException("Read-only")
    override fun updateCharacterStream(columnIndex: Int, x: java.io.Reader?, length: Int) = throw SQLException("Read-only")
    override fun updateCharacterStream(columnLabel: String?, x: java.io.Reader?, length: Int) = throw SQLException("Read-only")
    override fun updateCharacterStream(columnIndex: Int, x: java.io.Reader?, length: Long) = throw SQLException("Read-only")
    override fun updateCharacterStream(columnLabel: String?, x: java.io.Reader?, length: Long) = throw SQLException("Read-only")
    override fun updateCharacterStream(columnIndex: Int, x: java.io.Reader?) = throw SQLException("Read-only")
    override fun updateCharacterStream(columnLabel: String?, x: java.io.Reader?) = throw SQLException("Read-only")
    override fun updateObject(columnIndex: Int, x: Any?, scaleOrLength: Int) = throw SQLException("Read-only")
    override fun updateObject(columnIndex: Int, x: Any?) = throw SQLException("Read-only")
    override fun updateObject(columnLabel: String?, x: Any?, scaleOrLength: Int) = throw SQLException("Read-only")
    override fun updateObject(columnLabel: String?, x: Any?) = throw SQLException("Read-only")
    override fun insertRow() = throw SQLException("Read-only")
    override fun updateRow() = throw SQLException("Read-only")
    override fun deleteRow() = throw SQLException("Read-only")
    override fun refreshRow() = throw SQLException("Read-only")
    override fun cancelRowUpdates() = throw SQLException("Read-only")
    override fun moveToInsertRow() = throw SQLException("Read-only")
    override fun moveToCurrentRow() = throw SQLException("Read-only")
    override fun updateRef(columnIndex: Int, x: java.sql.Ref?) = throw SQLException("Read-only")
    override fun updateRef(columnLabel: String?, x: java.sql.Ref?) = throw SQLException("Read-only")
    override fun updateBlob(columnIndex: Int, x: java.sql.Blob?) = throw SQLException("Read-only")
    override fun updateBlob(columnLabel: String?, x: java.sql.Blob?) = throw SQLException("Read-only")
    override fun updateBlob(columnIndex: Int, x: java.io.InputStream?, length: Long) = throw SQLException("Read-only")
    override fun updateBlob(columnLabel: String?, x: java.io.InputStream?, length: Long) = throw SQLException("Read-only")
    override fun updateBlob(columnIndex: Int, x: java.io.InputStream?) = throw SQLException("Read-only")
    override fun updateBlob(columnLabel: String?, x: java.io.InputStream?) = throw SQLException("Read-only")
    override fun updateClob(columnIndex: Int, x: java.sql.Clob?) = throw SQLException("Read-only")
    override fun updateClob(columnLabel: String?, x: java.sql.Clob?) = throw SQLException("Read-only")
    override fun updateClob(columnIndex: Int, x: java.io.Reader?, length: Long) = throw SQLException("Read-only")
    override fun updateClob(columnLabel: String?, x: java.io.Reader?, length: Long) = throw SQLException("Read-only")
    override fun updateClob(columnIndex: Int, x: java.io.Reader?) = throw SQLException("Read-only")
    override fun updateClob(columnLabel: String?, x: java.io.Reader?) = throw SQLException("Read-only")
    override fun updateArray(columnIndex: Int, x: java.sql.Array?) = throw SQLException("Read-only")
    override fun updateArray(columnLabel: String?, x: java.sql.Array?) = throw SQLException("Read-only")
    override fun updateRowId(columnIndex: Int, x: java.sql.RowId?) = throw SQLException("Read-only")
    override fun updateRowId(columnLabel: String?, x: java.sql.RowId?) = throw SQLException("Read-only")
    override fun updateNString(columnIndex: Int, nString: String?) = throw SQLException("Read-only")
    override fun updateNString(columnLabel: String?, nString: String?) = throw SQLException("Read-only")
    override fun updateNClob(columnIndex: Int, nClob: java.sql.NClob?) = throw SQLException("Read-only")
    override fun updateNClob(columnLabel: String?, nClob: java.sql.NClob?) = throw SQLException("Read-only")
    override fun updateNClob(columnIndex: Int, reader: java.io.Reader?, length: Long) = throw SQLException("Read-only")
    override fun updateNClob(columnLabel: String?, reader: java.io.Reader?, length: Long) = throw SQLException("Read-only")
    override fun updateNClob(columnIndex: Int, reader: java.io.Reader?) = throw SQLException("Read-only")
    override fun updateNClob(columnLabel: String?, reader: java.io.Reader?) = throw SQLException("Read-only")
    override fun updateSQLXML(columnIndex: Int, xmlObject: java.sql.SQLXML?) = throw SQLException("Read-only")
    override fun updateSQLXML(columnLabel: String?, xmlObject: java.sql.SQLXML?) = throw SQLException("Read-only")
    override fun updateNCharacterStream(columnIndex: Int, x: java.io.Reader?, length: Long) = throw SQLException("Read-only")
    override fun updateNCharacterStream(columnLabel: String?, x: java.io.Reader?, length: Long) = throw SQLException("Read-only")
    override fun updateNCharacterStream(columnIndex: Int, x: java.io.Reader?) = throw SQLException("Read-only")
    override fun updateNCharacterStream(columnLabel: String?, x: java.io.Reader?) = throw SQLException("Read-only")
}
