package com.taskqueue.queue

import org.assertj.core.api.Assertions.assertThat
import org.h2.jdbcx.JdbcDataSource
import org.jdbi.v3.core.Jdbi
import org.jdbi.v3.core.kotlin.KotlinPlugin
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Clob
import java.time.Instant
import java.time.temporal.ChronoUnit
import java.util.UUID

/**
 * DAO tests using H2 in Oracle compatibility mode.
 *
 * Tests cover methods that use standard SQL or H2-Oracle-compatible functions (SYSTIMESTAMP).
 * Methods using NUMTODSINTERVAL or Oracle MERGE are excluded — those require Oracle integration tests.
 */
class TaskQueueDaoH2Test {

    private lateinit var jdbi: Jdbi
    private lateinit var dao: TaskQueueDao

    @BeforeEach
    fun setUp() {
        val ds = JdbcDataSource().apply {
            setURL("jdbc:h2:mem:test_${UUID.randomUUID()};MODE=Oracle;DB_CLOSE_DELAY=-1")
        }
        jdbi = Jdbi.create(ds).apply { installPlugin(KotlinPlugin()) }
        dao = TaskQueueDao(jdbi)

        jdbi.useHandle<Exception> { handle ->
            handle.execute(
                """
                CREATE TABLE TASK_QUEUE (
                    TASK_ID        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    PARENT_TASK_ID BIGINT,
                    TASK_TYPE      VARCHAR(64) NOT NULL,
                    PAYLOAD        CLOB,
                    STATUS         VARCHAR(16) DEFAULT 'PENDING' NOT NULL,
                    PRIORITY       INT DEFAULT 5,
                    DEADLINE_AT    TIMESTAMP,
                    SCHEDULED_AT   TIMESTAMP,
                    RETRY_COUNT    INT DEFAULT 0,
                    MAX_RETRIES    INT DEFAULT 3,
                    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    STARTED_AT     TIMESTAMP,
                    COMPLETED_AT   TIMESTAMP,
                    ERROR_MESSAGE  VARCHAR(4000),
                    ERROR_HISTORY  CLOB,
                    UNIQUE_KEY     VARCHAR(128),
                    CONSTRAINT CHK_STATUS CHECK (STATUS IN (
                        'PENDING','SCHEDULED','PROCESSING','RETRYABLE',
                        'DONE','CANCELLED','DISCARDED','EXPIRED'
                    )),
                    CONSTRAINT CHK_PRIORITY CHECK (PRIORITY BETWEEN 1 AND 9)
                )
                """.trimIndent()
            )
            handle.execute("CREATE UNIQUE INDEX IDX_TASK_UNIQUE_KEY ON TASK_QUEUE(UNIQUE_KEY)")
        }
    }

    // ── insertRootTask ──

    @Test
    fun `insertRootTask creates a task with default values`() {
        val taskId = dao.insertRootTask(taskType = "TEST_TYPE")

        assertThat(taskId).isGreaterThan(0)
        val row = selectTask(taskId)
        assertThat(row["STATUS"]).isEqualTo("PENDING")
        assertThat(row["TASK_TYPE"]).isEqualTo("TEST_TYPE")
        assertThat(row["PRIORITY"]).isEqualTo(5)
        assertThat(row["RETRY_COUNT"]).isEqualTo(0)
        assertThat(row["MAX_RETRIES"]).isEqualTo(3)
        assertThat(row["PARENT_TASK_ID"]).isNull()
        assertThat(row["PAYLOAD"]).isNull()
    }

    @Test
    fun `insertRootTask with all parameters`() {
        val deadline = Instant.now().plus(6, ChronoUnit.HOURS)
        val taskId = dao.insertRootTask(
            taskType = "FULL_TASK",
            payload = """{"key":"value"}""",
            priority = 2,
            deadlineAt = deadline,
        )

        val row = selectTask(taskId)
        assertThat(row["TASK_TYPE"]).isEqualTo("FULL_TASK")
        assertThat(row["PAYLOAD"]).isEqualTo("""{"key":"value"}""")
        assertThat(row["PRIORITY"]).isEqualTo(2)
        assertThat(row["DEADLINE_AT"]).isNotNull()
    }

    @Test
    fun `insertRootTask returns unique IDs for each insert`() {
        val id1 = dao.insertRootTask(taskType = "A")
        val id2 = dao.insertRootTask(taskType = "B")
        val id3 = dao.insertRootTask(taskType = "C")
        assertThat(setOf(id1, id2, id3)).hasSize(3)
    }

    // ── insertRootTaskUnique ──

    @Test
    fun `insertRootTaskUnique succeeds on first insert`() {
        val key = TaskQueueDao.generateUniqueKey("UNIQUE_TYPE", null)
        val taskId = dao.insertRootTaskUnique(
            taskType = "UNIQUE_TYPE",
            uniqueKey = key,
        )
        assertThat(taskId).isNotNull()
        assertThat(taskId).isGreaterThan(0)
    }

    @Test
    fun `insertRootTaskUnique returns null for duplicate key`() {
        val key = TaskQueueDao.generateUniqueKey("DUP_TYPE", "payload")
        val first = dao.insertRootTaskUnique(taskType = "DUP_TYPE", payload = "payload", uniqueKey = key)
        val second = dao.insertRootTaskUnique(taskType = "DUP_TYPE", payload = "payload", uniqueKey = key)

        assertThat(first).isNotNull()
        assertThat(second).isNull()
    }

    @Test
    fun `insertRootTaskUnique allows different keys`() {
        val key1 = TaskQueueDao.generateUniqueKey("TYPE", "p1")
        val key2 = TaskQueueDao.generateUniqueKey("TYPE", "p2")
        val first = dao.insertRootTaskUnique(taskType = "TYPE", payload = "p1", uniqueKey = key1)
        val second = dao.insertRootTaskUnique(taskType = "TYPE", payload = "p2", uniqueKey = key2)

        assertThat(first).isNotNull()
        assertThat(second).isNotNull()
    }

    // ── insertChildren ──

    @Test
    fun `insertChildren creates child tasks linked to parent`() {
        val parentId = dao.insertRootTask(taskType = "PARENT")
        val children = listOf(
            TaskEmitter.PendingTask("CHILD_A", """{"id":1}""", 3, null),
            TaskEmitter.PendingTask("CHILD_B", """{"id":2}""", 4, null),
        )

        dao.insertChildren(parentId, children)

        val childRows = jdbi.withHandle<List<Map<String, Any?>>, Exception> { handle ->
            handle.createQuery("SELECT * FROM TASK_QUEUE WHERE PARENT_TASK_ID = :pid")
                .bind("pid", parentId)
                .mapToMap()
                .list()
                .map { row ->
                    row.mapKeys { it.key.uppercase() }.mapValues { (_, v) ->
                        if (v is Clob) v.characterStream.readText() else v
                    }
                }
        }
        assertThat(childRows).hasSize(2)
        assertThat(childRows.map { it["TASK_TYPE"] }).containsExactlyInAnyOrder("CHILD_A", "CHILD_B")
        assertThat(childRows.all { it["STATUS"] == "PENDING" }).isTrue()
    }

    @Test
    fun `insertChildren with empty list is a no-op`() {
        val parentId = dao.insertRootTask(taskType = "PARENT")
        dao.insertChildren(parentId, emptyList())

        val count = jdbi.withHandle<Long, Exception> { handle ->
            handle.createQuery("SELECT COUNT(*) FROM TASK_QUEUE WHERE PARENT_TASK_ID = :pid")
                .bind("pid", parentId)
                .mapTo(Long::class.java)
                .one()
        }
        assertThat(count).isEqualTo(0)
    }

    // ── markDone ──

    @Test
    fun `markDone transitions PROCESSING to DONE`() {
        val taskId = insertTaskInStatus("PROCESSING")

        val result = dao.markDone(taskId)
        assertThat(result).isTrue()
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("DONE")
        assertThat(selectTask(taskId)["COMPLETED_AT"]).isNotNull()
    }

    @Test
    fun `markDone returns false if not in PROCESSING`() {
        val taskId = insertTaskInStatus("PENDING")
        val result = dao.markDone(taskId)
        assertThat(result).isFalse()
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("PENDING")
    }

    @Test
    fun `markDone is idempotent - second call returns false`() {
        val taskId = insertTaskInStatus("PROCESSING")
        assertThat(dao.markDone(taskId)).isTrue()
        assertThat(dao.markDone(taskId)).isFalse()
    }

    // ── markCancelled ──

    @Test
    fun `markCancelled transitions PROCESSING to CANCELLED with reason`() {
        val taskId = insertTaskInStatus("PROCESSING")

        val result = dao.markCancelled(taskId, "user requested cancellation")
        assertThat(result).isTrue()

        val row = selectTask(taskId)
        assertThat(row["STATUS"]).isEqualTo("CANCELLED")
        assertThat(row["ERROR_MESSAGE"]).isEqualTo("user requested cancellation")
        assertThat(row["COMPLETED_AT"]).isNotNull()
    }

    @Test
    fun `markCancelled returns false if not in PROCESSING`() {
        val taskId = insertTaskInStatus("DONE")
        assertThat(dao.markCancelled(taskId, "reason")).isFalse()
    }

    // ── markDiscarded ──

    @Test
    fun `markDiscarded transitions PROCESSING to DISCARDED with error history`() {
        val taskId = insertTaskInStatus("PROCESSING")

        val result = dao.markDiscarded(taskId, "NullPointerException: oops", 2)
        assertThat(result).isTrue()

        val row = selectTask(taskId)
        assertThat(row["STATUS"]).isEqualTo("DISCARDED")
        assertThat(row["ERROR_MESSAGE"] as String?).contains("NullPointerException")
        assertThat(row["COMPLETED_AT"]).isNotNull()

        val history = row["ERROR_HISTORY"] as String?
        assertThat(history).isNotNull()
        assertThat(history).startsWith("[{")
        assertThat(history).contains("\"attempt\":2")
        assertThat(history).contains("\"error\":")
    }

    @Test
    fun `markDiscarded appends to existing error history`() {
        val taskId = insertTaskInStatus("PROCESSING")

        // First discard
        dao.markDiscarded(taskId, "error1", 0)

        // Reset to PROCESSING to simulate another failure
        updateStatus(taskId, "PROCESSING")

        dao.markDiscarded(taskId, "error2", 1)

        val row = selectTask(taskId)
        val history = row["ERROR_HISTORY"] as String?
        assertThat(history).isNotNull()
        assertThat(history).startsWith("[{")
        // Should contain two entries
        assertThat(history!!.split("\"attempt\"")).hasSize(3) // 1 prefix + 2 entries
    }

    // ── markExpired ──

    @Test
    fun `markExpired transitions PENDING to EXPIRED`() {
        val taskId = insertTaskInStatus("PENDING")
        assertThat(dao.markExpired(taskId)).isTrue()
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("EXPIRED")
    }

    @Test
    fun `markExpired transitions PROCESSING to EXPIRED`() {
        val taskId = insertTaskInStatus("PROCESSING")
        assertThat(dao.markExpired(taskId)).isTrue()
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("EXPIRED")
    }

    @Test
    fun `markExpired returns false for terminal status`() {
        val taskId = insertTaskInStatus("DONE")
        assertThat(dao.markExpired(taskId)).isFalse()
    }

    // ── countByStatus ──

    @Test
    fun `countByStatus returns correct counts`() {
        insertTaskInStatus("PENDING")
        insertTaskInStatus("PENDING")
        insertTaskInStatus("PROCESSING")
        insertTaskInStatus("DONE")

        val counts = dao.countByStatus()
        assertThat(counts["PENDING"]).isEqualTo(2)
        assertThat(counts["PROCESSING"]).isEqualTo(1)
        assertThat(counts["DONE"]).isEqualTo(1)
    }

    @Test
    fun `countByStatus returns empty map for empty table`() {
        val counts = dao.countByStatus()
        assertThat(counts).isEmpty()
    }

    // ── expireOverdueTasks ──

    @Test
    fun `expireOverdueTasks expires pending tasks past deadline`() {
        val pastDeadline = Instant.now().minus(1, ChronoUnit.HOURS)
        val futureDeadline = Instant.now().plus(1, ChronoUnit.HOURS)

        val expired1 = insertTaskWithDeadline("PENDING", pastDeadline)
        val expired2 = insertTaskWithDeadline("PENDING", pastDeadline)
        val notExpired = insertTaskWithDeadline("PENDING", futureDeadline)
        val noDeadline = insertTaskInStatus("PENDING")

        val count = dao.expireOverdueTasks()
        assertThat(count).isEqualTo(2)

        assertThat(selectTask(expired1)["STATUS"]).isEqualTo("EXPIRED")
        assertThat(selectTask(expired2)["STATUS"]).isEqualTo("EXPIRED")
        assertThat(selectTask(notExpired)["STATUS"]).isEqualTo("PENDING")
        assertThat(selectTask(noDeadline)["STATUS"]).isEqualTo("PENDING")
    }

    @Test
    fun `expireOverdueTasks does not affect PROCESSING tasks`() {
        val pastDeadline = Instant.now().minus(1, ChronoUnit.HOURS)
        val taskId = insertTaskWithDeadline("PROCESSING", pastDeadline)

        dao.expireOverdueTasks()
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("PROCESSING")
    }

    // ── promoteScheduledTasks ──

    @Test
    fun `promoteScheduledTasks promotes RETRYABLE tasks with past scheduledAt`() {
        val taskId = insertTaskInStatus("RETRYABLE")
        // Set SCHEDULED_AT to the past
        setScheduledAt(taskId, Instant.now().minus(1, ChronoUnit.MINUTES))

        val count = dao.promoteScheduledTasks()
        assertThat(count).isEqualTo(1)
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("PENDING")
        assertThat(selectTask(taskId)["SCHEDULED_AT"]).isNull()
    }

    @Test
    fun `promoteScheduledTasks promotes SCHEDULED tasks with past scheduledAt`() {
        val taskId = insertTaskInStatus("SCHEDULED")
        setScheduledAt(taskId, Instant.now().minus(1, ChronoUnit.MINUTES))

        val count = dao.promoteScheduledTasks()
        assertThat(count).isEqualTo(1)
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("PENDING")
    }

    @Test
    fun `promoteScheduledTasks does not promote tasks with future scheduledAt`() {
        val taskId = insertTaskInStatus("RETRYABLE")
        setScheduledAt(taskId, Instant.now().plus(1, ChronoUnit.HOURS))

        val count = dao.promoteScheduledTasks()
        assertThat(count).isEqualTo(0)
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("RETRYABLE")
    }

    @Test
    fun `promoteScheduledTasks does not promote tasks without scheduledAt`() {
        val taskId = insertTaskInStatus("RETRYABLE")
        // SCHEDULED_AT is NULL

        val count = dao.promoteScheduledTasks()
        assertThat(count).isEqualTo(0)
    }

    @Test
    fun `promoteScheduledTasks does not promote PENDING tasks`() {
        val taskId = insertTaskInStatus("PENDING")
        setScheduledAt(taskId, Instant.now().minus(1, ChronoUnit.MINUTES))

        val count = dao.promoteScheduledTasks()
        assertThat(count).isEqualTo(0)
        assertThat(selectTask(taskId)["STATUS"]).isEqualTo("PENDING")
    }

    // ── Helpers ──

    private fun selectTask(taskId: Long): Map<String, Any?> {
        return jdbi.withHandle<Map<String, Any?>, Exception> { handle ->
            val row = handle.createQuery("SELECT * FROM TASK_QUEUE WHERE TASK_ID = :id")
                .bind("id", taskId)
                .mapToMap()
                .one()
            // Materialize CLOBs while connection is open, then normalize keys to uppercase
            row.mapKeys { it.key.uppercase() }
                .mapValues { (_, value) ->
                    when (value) {
                        is Clob -> value.characterStream.readText()
                        else -> value
                    }
                }
        }
    }

    private fun insertTaskInStatus(status: String): Long {
        return jdbi.withHandle<Long, Exception> { handle ->
            handle.createUpdate(
                """
                INSERT INTO TASK_QUEUE (TASK_TYPE, STATUS, CREATED_AT, UPDATED_AT)
                VALUES ('TEST', :status, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """.trimIndent()
            )
                .bind("status", status)
                .executeAndReturnGeneratedKeys("TASK_ID")
                .mapTo(Long::class.java)
                .one()
        }
    }

    private fun insertTaskWithDeadline(status: String, deadline: Instant): Long {
        return jdbi.withHandle<Long, Exception> { handle ->
            handle.createUpdate(
                """
                INSERT INTO TASK_QUEUE (TASK_TYPE, STATUS, DEADLINE_AT, CREATED_AT, UPDATED_AT)
                VALUES ('TEST', :status, :deadline, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """.trimIndent()
            )
                .bind("status", status)
                .bind("deadline", java.sql.Timestamp.from(deadline))
                .executeAndReturnGeneratedKeys("TASK_ID")
                .mapTo(Long::class.java)
                .one()
        }
    }

    private fun updateStatus(taskId: Long, status: String) {
        jdbi.useHandle<Exception> { handle ->
            handle.createUpdate("UPDATE TASK_QUEUE SET STATUS = :status WHERE TASK_ID = :id")
                .bind("status", status)
                .bind("id", taskId)
                .execute()
        }
    }

    private fun setScheduledAt(taskId: Long, scheduledAt: Instant) {
        jdbi.useHandle<Exception> { handle ->
            handle.createUpdate("UPDATE TASK_QUEUE SET SCHEDULED_AT = :scheduledAt WHERE TASK_ID = :id")
                .bind("scheduledAt", java.sql.Timestamp.from(scheduledAt))
                .bind("id", taskId)
                .execute()
        }
    }
}
